TaskBlog.PresentationLayer/ViewModels/ArticleViewModel.cs
using System;

namespace TaskBlog.PresentationLayer.ViewModels
{
    public class ArticleViewModel
    {
        public ArticleViewModel()
        {
            Tags = new TagViewModel[] { };
            Comments = new CommentViewModel[] { };
            DateTime = System.DateTime.UtcNow;
            TagsId = new int[] { };
        }

        public int Id { get; set; }

        public string UserId { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public bool IsConfirmed { get; set; }

        public DateTime? DateTime { get; set; }

        public int[] TagsId { get; set; }

        public string ShortDescription
        {
            get
            {
                if (Description.Length > 200)
                    return Description.Substring(0, 200);
                return Description;
            }
        }

        public TagViewModel[] Tags { get; set; }

        public CommentViewModel[] Comments { get; set; }

        public UserProfileViewModel User { get; set; }
    }
}

TaskBlog.PresentationLayer/Controllers/ArticleController.cs
using System.Linq;
using System.Web.Mvc;
using TaskBlog.BusinessLogicLayer.Interfaces;
using TaskBlog.BusinessLogicLayer.Services;
using TaskBlog.ViewModels;
using TaskBlog.PresentationLayer.Enums;

namespace TaskBlog.PresentationLayer.Controllers
{
    public class ArticleController : Controller
    {
        ArticleService _articleService;
        TagService _tagService;

        public ArticleController(IService<ArticleViewModel> articleService, IService<TagViewModel> tagService)
        {
            _articleService = articleService as ArticleService;
            _tagService = tagService as TagService;
        }

        // GET: Article
        public ActionResult Index()
        {
            var viewArticles = _articleService.GetConfirmed().OrderByDescending(a => a.DateTime).ToList();
            ViewBag.Title = "Популярные статьи";
            return View(viewArticles);
        }

        public ActionResult FilterArticles(string userId = null, ArticleFilter filter = ArticleFilter.All)
        {
            var viewArticles = (userId == null) ? _articleService.GetAll() : _articleService.GetByUserId(userId);
            ViewBag.Title = (userId == null) ? "Популярные статьи" : "Мои статьи";

            switch (filter)
            {
                case ArticleFilter.Confirmed:
                    viewArticles = viewArticles.Where(a => a.IsConfirmed);
                    break;

                case ArticleFilter.NotConfirmed:
                    viewArticles = viewArticles.Where(a => !a.IsConfirmed);
                    ViewBag.Title = "Неопубликованные статьи";
                    break;
            }
            
            return View("Index", viewArticles.ToList());
        }

        public ActionResult Show(int articleId)
        {
            var viewArticle = _articleService.GetById(articleId);
            return View(viewArticle);
        }

        public ActionResult Edit(int articleId)
        {
            ViewBag.Tags = _tagService.GetAll();
            var viewModel = _articleService.GetById(articleId);
            return View(viewModel);
        }

        public ActionResult Create()
        {
            ViewBag.Tags = _tagService.GetAll();
            return View();
        }

        public ActionResult Confirm(int articleId)
        {
            _articleService.Confirm(articleId);
            _articleService.Save();
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArticleViewModel article)
        {
            _articleService.Create(article, article.TagsId);
            _articleService.Save();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Update(ArticleViewModel article)
        {
            _articleService.Update(article, article.TagsId);
            _articleService.Save();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Delete(int articleId)
        {
            _articleService.Delete(articleId);
            _articleService.Save();
            return RedirectToAction("Index");
        }

        public ActionResult GetByTag(int tagId)
        {
            var viewArticles = _articleService.GetByTag(tagId).OrderByDescending(a => a.DateTime).ToList();
            return View("Index", viewArticles);
        }
    }
}

TaskBlog.PresentationLayer/Controllers/CommentController.cs
using System.Linq;
using System.Web.Mvc;
using TaskBlog.ViewModels;
using TaskBlog.BusinessLogicLayer.Interfaces;
using TaskBlog.BusinessLogicLayer.Services;
using Microsoft.AspNet.Identity;

namespace TaskBlog.PresentationLayer.Controllers
{
    public class CommentController : Controller
    {
        CommentService _service;

        public CommentController(IService<CommentViewModel> service)
        {
            _service = service as CommentService;
        }

        // GET: Article
        public ActionResult GetByArticleId(int articleId)
        {
            var viewModels = _service.GetByArticleId(articleId).OrderByDescending(a => a.DateTime).ToList();
            return View(viewModels);
        }

        public PartialViewResult Create(int parentId)
        {
            return PartialView("_Form", 
                new CommentViewModel() { ParentPostId = parentId, UserId = User.Identity.GetUserId<string>() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CommentViewModel comment)
        {
            _service.Create(comment);
            _service.Save();
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult Delete(int id)
        {
            _service.Delete(id);
            _service.Save();
            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

TaskBlog.PresentationLayer/Controllers/UserProfileController.cs
using System.Web.Mvc;
using TaskBlog.BusinessLogicLayer.Interfaces;
using TaskBlog.ViewModels;
using AutoMapper;

namespace TaskBlog.PresentationLayer.Controllers
{
    [Authorize]
    public class UserProfileController : Controller
    {
        IService<UserProfileViewModel> _service;
        IMapper _modelsMapper;

        public UserProfileController(IService<UserProfileViewModel> service)
        {
            _service = service;
        }

        // GET: UserProfile
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Show(string userId)
        {
            var viewModel = _service.GetById(userId);
            return View(viewModel);
        }
    }
}

TaskBlog.PresentationLayer/Views/Article/Create.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Добавить статью";
    var userId = User.Identity.GetUserId<string>();
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />
@using (Html.BeginForm("Create", "Article", FormMethod.Post))
{
    @Html.Partial("_Form", new TaskBlog.ViewModels.ArticleViewModel() { UserId = userId })
}

TaskBlog.PresentationLayer/Views/Article/Edit.cshtml
@using Microsoft.AspNet.Identity
@model TaskBlog.ViewModels.ArticleViewModel
@{
    ViewBag.Title = "Редактировать статью";
    var userId = User.Identity.GetUserId<string>();
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />
@using (Html.BeginForm("Update", "Article", FormMethod.Post))
{
    @Html.Partial("_Form", Model)
}

TaskBlog.PresentationLayer/Views/Article/Index.cshtml
@model IEnumerable<TaskBlog.ViewModels.ArticleViewModel>

<h2 class="text-center">@ViewBag.Title</h2>
<hr />
    @if (Model.Count() > 0)
    {
        @ArticleHelpers.ArticlesList(Model)
    }
    else
    {
        <div class="ms-empty">
            <span class="text-center">Не опубликовано ни одной статьи</span>
            @if (User.Identity.IsAuthenticated)
            {
                <p>@Html.ActionLink("Добавить статью", "Create", "Article")</p>
            }
        </div>
    }

TaskBlog.PresentationLayer/Views/Article/Show.cshtml
@using Microsoft.AspNet.Identity
@model TaskBlog.ViewModels.ArticleViewModel
@{
    ViewBag.Title = Model.Name;
    var currUserId = User.Identity.GetUserId<string>();
}

<h2>@ViewBag.Title</h2>
<p>
    Автор: 
    @Html.ActionLink(Model.User.FullName, "Show", "UserProfile", new { userId = Model.User.Id})
</p>
<hr/>
    <span>Категории: </span>
    <span class="ms-tags-panel">
        @foreach (var t in Model.Tags)
        {
            <span class="label label-success">@Html.ActionLink(t.Name, "SearchByTag", new { tagId = t.Id })</span>
        }
    </span>
<hr/>
<div>
    @Model.Description
</div>
@if(Model.UserId == currUserId)
{
    <hr/>
    @Html.ActionLink("Редактировать", "Edit", "Article", new { articleId = Model.Id }, new { @class = "btn-sm btn-success" })
    <span> | </span>
    @Html.ActionLink("Удалить", "Delete", "Article", new { articleId = Model.Id }, new { @class = "btn-sm btn-danger" })
}
<hr />
<h3 class="text-center">Комментарии</h3>
<hr />
<div class="comments-area">
    @CommentHelpers.CommentsList(Model.Comments)
    @if(User.Identity.IsAuthenticated && Model.IsConfirmed)
    {
        <h4>Оставить комментарий</h4>
        @Html.Partial("~/Views/Comment/_Form.cshtml", new TaskBlog.ViewModels.CommentViewModel() { ParentPostId = Model.Id, UserId = currUserId })
    }
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('.ms-cancel-comment').hide();
            $('.ms-add-comment').on('click', function () {
                var container = $(this).parents('div.comment');
                var formPlace = container.find(".form-place");
                var cancelRef = container.find(".ms-cancel-comment");
                var parentId = container.attr('id');
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("Create", "Comment", null)",
                    data: {parentId: parentId},
                success: function (data) {
                    container.find(".form-place:first").html(data);
                    cancelRef.show();
                }
                });
                $(this).hide();
            });

            $('.ms-cancel-comment').on('click', function (e) {
                $('.ms-add-comment').show();
                var container = $(this).parents('div.comment');
                var addRef = container.find(".ms-add-comment");
                var formPlace = container.find(".form-place");
                formPlace.html("");
                $(this).hide();
                addRef.show();
            })
        });
    </script>
}

TaskBlog.PresentationLayer/Views/Article/_Form.cshtml
@using Microsoft.AspNet.Identity
@model TaskBlog.ViewModels.ArticleViewModel
@{ 
    var tags = (ViewBag.Tags != null)
        ? ViewBag.Tags
        : new TaskBlog.ViewModels.TagViewModel[] { };
}

<div class="row">
    <div class="ms ms-form-area col-md-8">
        
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group"> 
                @Html.HiddenFor(model => model.Id, new { @value = User.Identity.GetUserId<string>() })
                @Html.HiddenFor(model => model.UserId, new { @value = User.Identity.GetUserId<string>()})             
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @placeholder = "Название статьи", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">       
                @*Html.DropDownListFor(model => model.TagsId, new MultiSelectList(tags, "Id", "Name", new[] { 1, 2}), new { @class = "selectpicker", @multiple = "multiple" })*@
                <select id="TagsId" name="TagsId" class="selectpicker" multiple>
                    @foreach(var t in tags)
                    {
                        <option value="@t.Id" @(Model.TagsId.Contains((int)t.Id) ? "selected" : "")>@t.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">                
                @Html.TextAreaFor(model => model.Description, new { @placeholder = "Описание статьи", @class = "form-control", @rows = "10" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })                   
            </div>
            <div class="form-group">
                <div>
                    <input type="submit" value="Предложить опубликовать" class="btn btn-success" />
                </div>
            </div>
        </div>
        
    </div>
</div>