TaskBlog.PresentationLayer/Controllers/ArticleController.cs
using System.Linq;
using System.Web.Mvc;
using TaskBlog.BusinessLogicLayer.Interfaces;
using TaskBlog.BusinessLogicLayer.Services;
using TaskBlog.ViewModels;
using TaskBlog.PresentationLayer.Enums;

namespace TaskBlog.PresentationLayer.Controllers
{
    public class ArticleController : Controller
    {
        ArticleService _articleService;
        TagService _tagService;

        public ArticleController(IService<ArticleViewModel> articleService, IService<TagViewModel> tagService)
        {
            _articleService = articleService as ArticleService;
            _tagService = tagService as TagService;
        }

        // GET: Article
        public ActionResult Index()
        {
            var viewArticles = _articleService.GetConfirmed().OrderByDescending(a => a.DateTime).ToList();
            ViewBag.Title = "Популярные статьи";
            return View(viewArticles);
        }

        public ActionResult FilterArticles(string userId = null, ArticleFilter filter = ArticleFilter.All)
        {
            var viewArticles = (userId == null) ? _articleService.GetAll() : _articleService.GetByUserId(userId);
            ViewBag.Title = (userId == null) ? "Популярные статьи" : "Мои статьи";

            switch (filter)
            {
                case ArticleFilter.Confirmed:
                    viewArticles = viewArticles.Where(a => a.IsConfirmed);
                    break;

                case ArticleFilter.NotConfirmed:
                    viewArticles = viewArticles.Where(a => !a.IsConfirmed);
                    ViewBag.Title = "Неопубликованные статьи";
                    break;
            }
            
            return View("Index", viewArticles.ToList());
        }

        public ActionResult Show(int articleId)
        {
            var viewArticle = _articleService.GetById(articleId);
            return View(viewArticle);
        }

        public ActionResult Edit(int articleId)
        {
            ViewBag.Tags = _tagService.GetAll();
            var viewModel = _articleService.GetById(articleId);
            return View(viewModel);
        }

        public ActionResult Create()
        {
            ViewBag.Tags = _tagService.GetAll();
            return View();
        }

        public ActionResult Confirm(int articleId)
        {
            _articleService.Confirm(articleId);
            _articleService.Save();
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArticleViewModel article)
        {
            _articleService.Create(article, article.TagsId);
            _articleService.Save();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Update(ArticleViewModel article)
        {
            _articleService.Update(article, article.TagsId);
            _articleService.Save();
            return RedirectToAction("Index");
        }

        [Authorize]
        public ActionResult Delete(int articleId)
        {
            _articleService.Delete(articleId);
            _articleService.Save();
            return RedirectToAction("Index");
        }

        public ActionResult GetByTag(int tagId)
        {
            var viewArticles = _articleService.GetByTag(tagId).OrderByDescending(a => a.DateTime).ToList();
            return View("Index", viewArticles);
        }
    }
}

TaskBlog.PresentationLayer/Controllers/TagController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using TaskBlog.ViewModels;
using TaskBlog.BusinessLogicLayer.Interfaces;
using TaskBlog.BusinessLogicLayer.Services;

namespace TaskBlog.PresentationLayer.Controllers
{
    public class TagController : Controller
    {
        TagService _service;

        public TagController(IService<TagViewModel> service)
        {
            _service = service as TagService;
        }

        // GET: Article
        [Authorize]
        public ActionResult Index()
        {
            var viewModels = _service.GetAll().OrderBy(a => a.Name).ToList();
            return View(viewModels);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TagViewModel tag)
        {
            _service.Create(tag);
            _service.Save();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMany(string tags)
        {
            var t = tags.Split(new char[] { ','}, StringSplitOptions.RemoveEmptyEntries);
            _service.CreateMany(t);
            _service.Save();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            _service.Delete(id);
            _service.Save();
            return RedirectToAction("Index");
        }
    }
}

TaskBlog.PresentationLayer/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="navbar ms-navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("TaskBlog", "Index", "Article", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Статьи", "Index", "Article")</li>
                        <li>@Html.ActionLink("Категории", "Index", "Tag")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="jumbotron text-center">
            <h1>Simple blog</h1>
            <p>All interesting news!</p>
        </div>
    </header>
    <div class="container body-content">
        <div class="row">
            <aside class="ms-sidebar col-md-2">
                <h3 class="text-center">Меню пользователя</h3>
                @Html.Partial("~/Views/UserProfile/_Menu.cshtml");
            </aside>
            <div class="ms-main col-md-10">
                @RenderBody()
            </div>
        </div>
    </div>
    <hr />
    <footer class="ms-footer">
        <p>&copy; @DateTime.Now.Year - Developed by Khalimonov Stanislav</p>
        <a href="#">Back to top</a>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TaskBlog.PresentationLayer/Views/Shared/_Layout.cshtml
@{ 
    var currUser = HttpContext.Current.User.Identity;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="navbar ms-navbar">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("TaskBlog", "Index", "Article", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @*@if (User.IsInRole("admin"))
                        {
                            <li>@Html.ActionLink("Статьи", "Index", "Article")</li>
                            <li>@Html.ActionLink("Категории", "Index", "Tag")</li>
                        }*@
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="jumbotron text-center">
            <h1>Simple blog</h1>
            <p>All interesting news!</p>
        </div>
    </header>
    <div class="container body-content">
        <div class="row">
            <aside class="col-md-2">
                @Html.Partial("~/Views/UserProfile/_Menu.cshtml");
            </aside>
            <div class="main col-md-10">
                @RenderBody()
            </div>
            @*<div class="col-md-2">
                @Html.Partial("_Menu");
                @Html.Action("RandomVote", "Questionary");
            </div>*@
        </div>
    </div>
    <hr />
    <footer class="ms-footer">
        <p>&copy; @DateTime.Now.Year - Developed by Khalimonov Stanislav</p>
        <a href="#">Back to top</a>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>